### PR TITLE
Patch test for blob-run-mode

### PR DESCRIPTION
**Pull request by tabokie**
Newly introduced fallback mode of blob-run-mode is causing `Missing Blob File` fatal error, thus this PR adds more multi-threaded test around blob-run-mode setting. So far no bug is caught by unit test, Any idea on more solid test is welcome.

misc: fix file permission setting, fix SetOptions test in db_test.

### CODE REVIEW

**Comment by Connor1996** [comment]
How it cause `Missing blob file`?

**Comment by tabokie** [comment]
> How it causes `Missing blob file`?

For now use `tikv-ctl` to enter `fallback` mode while inserting into tikv will cause `Missing Blob File`.

**Comment by yiwu-arbug** [comment]
I reproduced the issue and found out why. The line here need to ignore files that has been GC, otherwise it will fail compaction. https://github.com/pingcap/titan/blob/master/src/table_builder.cc#L32

**Comment by tabokie** [comment]
Great! I will add GC invocation to strengthen unittest later.

**Comment by yiwu-arbug** [comment]
issue fixed by #30

**Pull request closed without merging**
