### PR TITLE
change codecov comment style

### PR DESCRIPTION
**Pull request by yiwu-arbug**
codecov comment on every PR, which is a bit annoying. try to disable it. 

Signed-off-by: Yi Wu <yiwu@pingcap.com>

### CODE REVIEW

**Comment by Connor1996** [comment]
I think invoking it on every PR is fine🤣So how to get the report after disabling it?

**Comment by yiwu-arbug** [comment]
click on the codecov badge icon and select pulls. I think we don't necessary need to worry about code coverage for every PR?
Screen Shot 2019-05-14 at 8 41 14 PM

**Comment by Connor1996** [comment]
The codecov report enforces us to care about the coverage and make sure at least not letting it drop when merging PR, especially for some breaking changes. If we don't trigger it actively, I think we would hardly to click on that icon.
And TiDB and PD show the codecov report on every PR.

**Comment by yiwu-arbug** [comment]
Changed the config to keep the codecov comment but only showing a summary.

**Pull request merged**
